### ISSUE TITLE
Wrong BB-code output

### ISSUE THREAD

**Issue by aNNiMON** [White-Oak/md2bb#1]
Here's a few examples that produces wrong bb-code

| md code | bb code |
| --- | --- |
| `***bold-italic***` | `[b][i]bold-italic[/b][/i]` |
| `## (A Tiny) Bytecode Refresher` | `[/b][/center]enter][b[/url] Bytecode Refresher` |
| &#x60;&#x60;&#x60;java<br>class Point {}<br>&#x60;&#x60;&#x60; | [code rust]java<br>class Point {}<br>[/code] |
| `It also includes information about the variable *types*... There is another, similar table called [LocalVariableTypeTable](http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html) that contains similar information...` | `It also includes information about the variable [url=http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html]i]types[/i]... There is another, similar table called [LocalVariableTypeTable[/url] that contains similar information...` |

---

**_bold-italic**_
## (A Tiny) Bytecode Refresher

``` java
class Point {}
```

It also includes information about the variable _types_... There is another, similar table called [LocalVariableTypeTable](http://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html) that contains similar information...
- [x] bold-italic
- [x] Incorrect order of rules 
- [x] different languages for code blocks
- [x] Incorrect order of rules (Still shouldn't have been a problem, hope tests will cover that one as well)
- [x] Tests (I hope I could go without them, I'm wrong! Shame on me)

**Comment by White-Oak** [comment]
Thanks for an issue!

I've added a tracking list to the end of your text, I hope you're not against it.
